USE [xxxx] -- Add TableName
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Certificates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreationDate] [datetime] NOT NULL CONSTRAINT [DF_Certificates_CreationDate]  DEFAULT (getdate()),
	[DomainName] [nvarchar](254) NOT NULL,
	[DomainDepth] [int] NOT NULL,
	[IpAddress] [varchar](45) NOT NULL,
	[Port] [int] NOT NULL,
	[CheckTime] [datetime] NOT NULL,
	[Reachable] [nvarchar](8) NULL,
	[Grade] [char](2) NOT NULL,
	[FutureGrade] [char](2) NULL,
	[HasWarnings] [bit] NULL,
	[IsExceptional] [bit] NULL,
	[RequestDuration] [int] NOT NULL,
	[CertSubject] [nvarchar](max) NOT NULL,
	[CommonName] [nvarchar](max) NULL,
	[AltNames] [nvarchar](max) NOT NULL,
	[AltNameCount] [int] NOT NULL,
	[PrefixSupport] [bit] NOT NULL,
	[Issuer] [nvarchar](max) NOT NULL,
	[NotAfter] [datetime] NOT NULL,
	[NotBefore] [datetime] NOT NULL,
	[SignatureAlg] [nvarchar](64) NULL,
	[KeyAlg] [nvarchar](64) NOT NULL,
	[KeySize] [int] NOT NULL,
	[ValidationType] [nchar](5) NOT NULL,
	[IsSgc] [int] NOT NULL,
	[RevocationInfo] [int] NOT NULL,
	[ChainLength] [int] NOT NULL,
	[ChainSha1Hashes] [nvarchar](max) NULL,
	[ChainPinSha256] [nvarchar](max) NULL,
	[ChainIssuers] [nvarchar](max) NULL,
	[ChainData] [nvarchar](max) NULL,
	[IsTrusted] [int] NOT NULL,
	[SupportsSSL20] [bit] NOT NULL,
	[SupportsSSL30] [bit] NOT NULL,
	[SupportsTLS10] [bit] NOT NULL,
	[SupportsTLS11] [bit] NOT NULL,
	[SupportsTLS12] [bit] NOT NULL,
	[Suites] [nvarchar](max) NOT NULL,
	[SuiteCount] [int] NOT NULL,
	[SuitesInOrder] [bit] NULL,
	[ServerSignature] [nvarchar](max) NULL,
	[DebianFlawed] [bit] NULL,
	[SessionResumption] [int] NOT NULL,
	[RenegSupport] [int] NULL,
	[ChainIssues] [int] NOT NULL,
	[EngineVersion] [nvarchar](64) NOT NULL,
	[CriteriaVersion] [nvarchar](64) NOT NULL,
	[CrlUris] [nvarchar](max) NOT NULL,
	[OcspUris] [nvarchar](max) NOT NULL,
	[VulnBEAST] [bit] NULL,
	[Compression] [int] NULL,
	[NpnSupport] [bit] NULL,
	[NpnProtocols] [nvarchar](max) NULL,
	[SessionTickets] [int] NULL,
	[OcspStapling] [bit] NULL,
	[SniRequired] [bit] NULL,
	[HttpStatusCode] [int] NULL,
	[HttpForwarding] [nvarchar](max) NULL,
	[KeyStrength] [int] NULL,
	[Sims] [nvarchar](max) NULL,
	[ForwardSecrecy] [int] NULL,
	[Heartbeat] [bit] NULL,
	[Heartbleed] [bit] NULL,
	[Poodle] [bit] NULL,
	[PoodleTls] [int] NULL,
	[Logjam] [bit] NULL,
	[Freak] [bit] NULL,
	[OpenSslCcs] [int] NULL,
	[DhYsReuse] [bit] NULL,
	[DhPrimeCount] [int] NULL,
	[DhPrimeList] [nvarchar](max) NULL,
	[DhUsesKnownPrimes] [int] NULL,
	[SupportsRc4] [bit] NULL,
	[Rc4WithModern] [bit] NULL,
	[HstsPolicyMaxAge] [int] NULL,
	[HstsPolicyHeader] [nvarchar](max) NULL,
	[HstsPolicyStatus] [nvarchar](max) NULL,
	[HstsPolicyIncludeSubdomains] [nvarchar](max) NULL,
	[HstsPolicyPreload] [nvarchar](max) NULL,
	[HstsPolicyDirectives] [nvarchar](max) NULL,
	[HpkpPolicy] [nvarchar](max) NULL,
	[HpkpRoPolicy] [nvarchar](max) NULL,
	[HasSct] [bit] NULL,
	[Rc4Only] [bit] NULL,
	[ChaCha20Preference] [bit] NULL,
	[DrownVulnerable] [bit] NULL,
	[MustStaple] [int] NULL,
	[OpenSSLLuckyMinus20] [int] NULL,
	[SecurityHeadersGrade] [nvarchar](10) NULL,
	[SecurityHeadersXFrameOptions] [nvarchar](max) NULL,
	[SecurityHeadersStrictTransportSecurity] [nvarchar](max) NULL,
	[SecurityHeadersXContentTypeOptions] [nvarchar](max) NULL,
	[SecurityHeadersXXSSProtection] [nvarchar](max) NULL,
	[SecurityHeadersContentSecurityPolicy] [nvarchar](max) NULL,
	[SecurityHeadersReferrerPolicy] [nvarchar](max) NULL,
	[ObservatoryRating] [nvarchar](10) NULL,
	[ObservatoryPassFail] [nvarcahr](10) NULL,
	[ObservatoryIssues] [nvarchar] (max) NULL,
 CONSTRAINT [PK_Certificates] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
