CREATE TABLE [dbo].[Unreachable](
	[ScanID] [int] NOT NULL,
	[DomainID] [int] NOT NULL,
	[DNSError] [bit] NOT NULL,
 CONSTRAINT [PK_Unreachable] PRIMARY KEY CLUSTERED 
(
	[ScanID] ASC,
	[DomainID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO


